#!/usr/bin/env bash
docker-compose -f docker-compose.yml up -d --build
echo "
===================== 🚀 Done 🚀 ===================

      Created by Mirosław Małaczek

===================== 🚀 Done 🚀 ==================="
